### ISSUE TITLE
Not working on Windows Server 2022

### ISSUE THREAD

**Issue by carlos-suarez** [bp2008/WebProxy#1] opened 2023-09-27 01:04 UTC
Dowloaded windows zip (1.26.1.0) installer and followed instructions, installed .net6 runtime (6.0.22-win-x64), when running WebProxy.exe no window opens but process can be seen in Task Manager.

**Comment by bp2008** [comment] 2023-09-27 15:08
Interesting.  Indeed something seems to be broken on Server 2022 and also on another Win11 machine I have.  The WebProxy.exe process runs but hangs and the service manager GUI does not appear, nothing gets logged, and the settings file it outputs (in `C:\ProgramData\WebProxy`) is missing all the initial auto-configuration stuff which gives me some clues about where the hangup might be.  I'll see if I can figure this out this morning.

**Comment by carlos-suarez** [comment] 2023-09-27 15:12
thanks @bp2008 .., Win10 works right? I'm building a Win10 box right now because I want to test your proxy and see if it helps with my use case :-) .. I tried to do linux but I'm clueless there and event to I got to run everything I never got it to open admin command but that's probably on my end since my linux skills are extremely limited hehe

**Comment by bp2008** [comment] 2023-09-27 15:31
It turns out the bug was a deadlock and relatively easy to fix.  It would have affected all versions of Windows.  Not sure why it wasn't affecting Linux, which is the only OS I've been deploying on recently.

Fixed in [WebProxy 1.26.2](https://github.com/bp2008/WebProxy/releases/tag/1.26.2).

**Closed as completed by bp2008** 2023-09-27 15:31 UTC

**Comment by bp2008** [comment] 2023-09-27 15:33
Hmm.  As far as I can tell it likely affected Linux too.  But since I haven't apparently deployed the app on any new machines since I introduced the bug, I just never noticed.  How embarrassing.

The code path leading to this deadlock would only occur during service startup when it had to add things to the settings file (which it does upon the first launch to configure the admin console's web endpoint).

**Comment by bp2008** [comment] 2023-09-27 15:36
Also yes, to be clear, Win10 works.

**Comment by carlos-suarez** [comment] 2023-09-27 15:40
oh no worries.. I've had my share of "I never touched that" myself LOL.. excited I found your tool which I think is going to help me :-) .. can I and how would I get in touch if I have questions? is here in this topic fine? and thanks for the quick turn-around... I really appreciate it!

**Comment by bp2008** [comment] 2023-09-27 15:41
Yes, right here is fine.  I get email notifications.

**Comment by carlos-suarez** [comment] 2023-09-27 18:05
Ok so if you bear with me for 2 mins I want to explain my use case and if you can kindly let me know if what I need is doable before I got down the rabbit hole trying to fully understand your tool that'd be great.  Hope that's ok.

I have let's say 5 clients (iPhones) which I already connect to a proxy (Fiddler Proxy Classic) so I can intercept HTTPS calls and modify requests/responses depending on the call.  That works fine but now I need each client to be presented with a different IP to the different end-points they're calling, it doesn't need to be the actual IP of the client but is should be a valid one from the server of course and I can't use X-Forwarded-For header because that still just presents the default IP only.  Basically the end-points should see the requests coming from different IP for each client so I want to have 5 IPs added to my NIC but Fiddler doesn't have a provision to force a different IP per request or client. It can be configured to use an Egrees IP other than the default but it'll be for all the requests (and again X-Forwarded-For is not an option).

I know with .Net it is possible to bind the IP you want to use to send a request out which is why I started looking for some C# proxy I could hopefully open-source so I could customize the implementation if not there, I just don't have the expertise to build one on my own,  specially because of the TLS certificates and all that which is beyond my level.  I've tried other solutions like HttpToolkit/Mockttp and Nginx but those didn't work or I couldn't make it work at least.

I could just go the easy way and just create 5 servers but 5 is not a fix number so I need something little more easily scalable where I hopefully just keep adding IPs and/or NICs if I want 10, 50 or 100 at some point.

Is that doable with your proxy?  I gave it a quick go but couldn't even make it work for plain HTTP without asking for credentials on the client and when started changing settings I broke it and not even uninstalling and re-installing helps anymore .. that after I broke it like 3 times but was able to re-install LOL

Hope I'm not taking much of your time and I'd appreciate if you can help :-)

Thanks!

**Comment by bp2008** [comment] 2023-09-27 18:36
First of all, the Install/Uninstall button in the Service Manager only creates/removes the Windows Service registration.  It doesn't actually delete the configuration data.  If you want to nuke the settings and start over fresh, click the "Open Data Folder" button in the service manager, then delete the `Settings.json` file.  This should of course be done when the service is not running.

I want to see if I understand your goal correctly.  Because all your client connections are going through Fiddler, that is making your clients appear to all share the same IP address, from the perspective of the destination server.  You are trying to make it so that each client's traffic appears to originate from a different IP address.  Correct?

> I can't use X-Forwarded-For header because that still just presents the default IP only

You say you can't use the `X-Forwarded-For` header to solve this, but I don't understand why.  This is exactly the sort of thing the `X-Forwarded-For` header was designed to solve.  Are you saying that the final destination web service does not support reading the client IP from `X-Forwarded-For` and you can't get that capability added?  Or are you saying that Fiddler can't inject the X-Forwarded-For header appropriately?

Practically any reverse proxy server can inject an `X-Forwarded-For` header since it is such a common requirement.  However I think you would have trouble connecting WebProxy to Fiddler because WebProxy uses a custom HTTP client which ironically does not support making outgoing connections via a classic HTTP proxy server.  WebProxy itself is a "reverse proxy" server, in other words a transparent proxy, which is something very different from a classic HTTP proxy server which I believe uses https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/CONNECT  (WebProxy doesn't support that at all).  You can see [right here](https://github.com/bp2008/BPUtil/blob/d1ee304b676765082b56735663965e6d97e34a82/BPUtil/SimpleHttp/Client/ProxyClient.cs#L597) the code which makes the outgoing connection when proxying a request, and it just uses .NET's TcpClient class which is completely unaware of the HTTP protocol or proxy servers.

**Comment by bp2008** [comment] 2023-09-27 18:40
For a WebProxy usage example, look at this thread: https://ipcamtalk.com/threads/webproxy-gui-based-alternative-to-stunnel.72203/  It is a guide tailored for a specific program, but nonetheless demonstrates how to set up an entrypoint and exitpoint, and map them to each other via a route.

I'm just not sure it will do you much good.  I'd need to understand your problem better.

**Comment by carlos-suarez** [comment] 2023-09-27 18:56
> Are you saying that the final destination web service does not support reading the client IP from X-Forwarded-For and you can't get that capability added? Or are you saying that Fiddler can't inject the X-Forwarded-For header appropriately?

Fiddler is totally capable of inserting the X-Forwarded-For, the APIs have a challenge to the sign-in process external to them, not sure the complete details but it doesn't like when it finds out that multiple accounts come from the same IP and that challenge explicitly ignores or denies access when that header is presented.  We have worked around this but installing fiddler in different small machines but would prefer to have a single more robust machine and add IPs to it if possible.  I'll check out those links also.

**Comment by bp2008** [comment] 2023-09-27 19:25
Well you may be able to kludge something together by doing a custom build of WebProxy but it could be very tricky even if you're comfortable working with C# projects.  Although it would be convenient, it is unlikely that WebProxy can entirely replace Fiddler for your purposes, as there's not very much capability yet to modify outgoing requests or incoming responses.

You could at least make the outgoing connections use a different local IP address by modifying BPUtil's ProxyClient class where it makes the outgoing connection (https://github.com/bp2008/BPUtil/blob/d1ee304b676765082b56735663965e6d97e34a82/BPUtil/SimpleHttp/Client/ProxyClient.cs#L597).  You could change the TcpClient constructor to the one that accepts an IPEndPoint specifying the local endpoint to use for the outgoing connection.  You would also need to disable keep-alive for the outgoing connections so that every request would create its own connection instead of reusing any (which would most likely be using the wrong local IP endpoint).   This is a setting exposed via WebProxy's admin console.  It is also a bool flag in the ProxyOptions object in the code above.

**Comment by carlos-suarez** [comment] 2023-09-27 20:33
> it is unlikely that WebProxy can entirely replace Fiddler for your purposes, as there's not very much capability yet to modify outgoing requests or incoming responses.

Correct .. which is why my plan is to keep Fiddler doing the modifications but pass the requests down to WebProxy with a custom header identifying the client so it can be used to determine the IP and removing the header before sending the request of course ... WebProxy would get the request already modified and once the response makes it back to Fiddler it can then do the changes before sending back to the client.. I know is a long trip but I kind of tested it already by using two instances of fiddler and response time to client is acceptable.

Thanks for pointing the specific methods I'd need to focus on, I'll keep trying and see how far I can go.

Worse come worse if I'm not able to solve it on my own are you open to help? we have a small budget for this depending on your fees :-p

**Comment by bp2008** [comment] 2023-09-27 20:58
Sure I am open to help.  You'd be the first person I'm aware of actually using this project besides me.

I think yours is such a strange need that it would be awkward to implement in a generally-useful manner unfortunately.  By that I mean, the feature would be useful only to you and nobody else. LOL.  

There are plenty of legitimate reasons why a person might want outgoing traffic to come from a specific IP address and not let the OS choose one automatically (since often there are multiple available such as when using IPv6).  So I am not opposed to adding the ability to choose the outgoing IP on a per-Exitpoint basis.  I'd probably implement that as a dropdown box where all the local IP addresses are options to be selected.

Your unusual requirement is that the network client be able to choose via HTTP header which IP will be used by the reverse proxy server for its outgoing connection.  I would think to implement that as a special option at the end of the options in the dropdown list.  E.g.
```
127.0.0.1
192.168.0.100
192.168.0.101
192.168.0.102
192.168.0.103
192.168.0.104
192.168.0.105
Read from request header "X-Outgoing-Interface"
```

If you want to take a shot at proving the concept works for you, I refer again to the ProxyClient source, line 266: https://github.com/bp2008/BPUtil/blob/d1ee304b676765082b56735663965e6d97e34a82/BPUtil/SimpleHttp/Client/ProxyClient.cs#L266

That is where the `Connect` method is called.  You could call `p.Request.Headers.Get("X-Outgoing-Interface")`  (returns a string), create an IPEndPoint from it, and pass it into the Connect method where you could then pass it into the TcpClient constructor.  Take care to disable keep-alive in the Exitpoint configuration as I have previously mentioned.

**Comment by carlos-suarez** [comment] 2023-09-28 00:20
I know right!? lol .. yeah it's a weird use case but believe me I have one hehe.

I'll give it a try and let you know.  Even if I manage to make it work as an initial POC I'd probably ask you to make for us a more compact version that's quick and easy to run in very slim servers.

Thanks again!

**Comment by bp2008** [comment] 2023-09-28 01:31
Well I have been running WebProxy in a 1 GB RAM ubuntu server VM for a while and it seems to be fine, usually around 160 MB memory usage (only about 5-10 MB of heap memory usage ... dotnet is a pig).  I am sure it would be fine on a half gig single core virtual machine for light loads of no more than a few dozen concurrent connections (and probably work to well into the hundreds of concurrent connections, not sure).
